from django.db import models
#creating database for pokemon cards

class project(models.Model):
    idd = models.CharField(editable=False, max_length=10)
    name = models.CharField(max_length=100)
    imageUrl = models.CharField(max_length=100)
    imageUrlHiRes = models.CharField(max_length=100)
    supertype = models.CharField(max_length=100)
    subtype = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    rarity = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    set = models.CharField(max_length=100)
    setCode = models.CharField(max_length=100)
    text = models.CharField(max_length=1000, null=True)
    nationalPokedexNumber = models.CharField(max_length=100, null=True)
    types = models.CharField(max_length=100, null=True)
    hp = models.CharField(max_length=100, null=True)
    retreatCost = models.CharField(max_length=100, null=True)
    convertedRetreatCost = models.CharField(max_length=100, null=True)
    attackDamage = models.CharField(max_length=100, null=True)
    attackCost = models.CharField(max_length=100, null=True)
    attackName = models.CharField(max_length=100, null=True)
    attackText = models.CharField(max_length=100, null=True)
    weaknesses = models.CharField(max_length=100, null=True)
    resistances = models.CharField(max_length=100, null=True)
    abilityName = models.CharField(max_length=100, null=True)
    abilityText = models.CharField(max_length=100, null=True)
    abilityType = models.CharField(max_length=100, null=True)
    evolvesFrom = models.CharField(max_length=100, null=True)
