# Generated by Django 3.1 on 2020-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(editable=False, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=100)),
                ('imageUrlHiRes', models.CharField(max_length=100)),
                ('supertype', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('set', models.CharField(max_length=100)),
                ('setCode', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('nationalPokedexNumber', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('hp', models.CharField(max_length=100)),
                ('retreatCost', models.CharField(max_length=100)),
                ('convertedRetreatCost', models.CharField(max_length=100)),
                ('attackDamage', models.CharField(max_length=100)),
                ('attackCost', models.CharField(max_length=100)),
                ('attackName', models.CharField(max_length=100)),
                ('attackText', models.CharField(max_length=100)),
                ('weaknesses', models.CharField(max_length=100)),
                ('resistances', models.CharField(max_length=100)),
                ('abilityName', models.CharField(max_length=100)),
                ('abilityText', models.CharField(max_length=100)),
                ('abilityType', models.CharField(max_length=100)),
                ('evolvesFrom', models.CharField(max_length=100)),
            ],
        ),
    ]
