# Generated by Django 3.1 on 2020-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nationalPokedexNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
