# Generated by Django 3.1 on 2020-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0003_auto_20200807_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
